### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by postables** [samwiseg0/zabbix#7]
Although I found the link to this on the zabbix share website, unlicensed github repositories do not grant permission to be used, see https://choosealicense.com/no-permission/.

This is amazing and saved myself a lot of time :D

I maintain a [repository](https://github.com/RTradeLtd/misc) I use to centrally locate various scripts and zabbix templates my company use, which includes a link to this repository and template. If requested I will remove.

**Comment by samwiseg0** [comment]
I have bene meaning to add one. Thanks for the reminder.
